export const OBTENER_UNIVERSITARIOS = "OBTENER_UNIVERSITARIOS"
export const AGREGAR_UNIVERSITARIO = "AGREGAR_UNIVERSITARIO"
export const ERROR_UNIVERSITARIO = "UNIVERSITARIO_ERROR"
export const ELIMINAR_UNIVERSITARIO = "ELIMINAR_ESTUDIANTE"
export const EDITAR_UNIVERSITARIO = "EDITAR_ESTUDIANTE"
export const BUSQUEDA_UNIVERSITARIO = "BUSQUEDA_UNIVERSITARIO"
export const LIMPIAR_FORMULARIO = "LIMPIAR_FORMULARIO"

export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";