export const OBTENER_UNIVERSITARIOS = "OBTENER_UNIVERSITARIOS";
export const AGREGAR_UNIVERSITARIO = "AGREGAR_UNIVERSITARIO";
export const ERROR_UNIVERSITARIO = "UNIVERSITARIO_ERROR";
export const ELIMINAR_UNIVERSITARIO = "ELIMINAR_ESTUDIANTE";
export const EDITAR_UNIVERSITARIO = "EDITAR_ESTUDIANTE";
export const BUSQUEDA_UNIVERSITARIO = "BUSQUEDA_UNIVERSITARIO";
export const LIMPIAR_UNIVERSITARIO_BUSCADO = "LIMPIAR_UNIVERSITARIO_BUSCADO";

export const LIMPIAR_FORMULARIO = "LIMPIAR_FORMULARIO";

export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";

export const OBTENER_FRENTES = "OBTENER_FRENTES";
export const AGREGAR_FRENTE = "AGREGAR_FRENTE";
export const ELIMINAR_FRENTE = "ELIMINAR_FRENTE";
export const EDITAR_FRENTE = "EDITAR_FRENTE";
export const ERROR_FRENTE = "ERROR_FRENTE";

export const LIMPIAR_MENSAJE = "LIMPIAR_MENSAJE";

export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CERRAR_SESION = "CERRAR_SESION";

export const ENCARGADO_HABILITA_VOTANTE = "ENCARGADO_HABILITA_VOTANTE";
export const VERIFICADOR_HABILITA_VOTANTE = "VERIFICADOR_HABILITA_VOTANTE";
export const AUTORIZANDO_VOTANTE = "AUTORIZANDO_VOTANTE";
export const ERROR_VOTANTE = "ERROR_VOTANTE";
export const LIMPIAR_DESCRIPCION_RECHAZO = "LIMPIAR_DESCRIPCION_RECHAZO";
export const ACTUALIZAR_VOTANTE = "ACTUALIZAR_VOTANTE";
export const OBTENER_VOTANTES = "OBTENER_vOTANTES";

export const LIMPIAR_DATOS = "LIMPIAR_DATOS";
